files structure: move src_paths as a dynamic property, add remove
mkdocs/mkdocs pull request #2305
Opened 2021-02-15 12:18 UTC by ultrabug

Plugins wishing to manipulate the Files structure have an append
method but can't dynamically work on src_paths since it's computed
once on Files instanciation

This commits allows plugins to manipulate Files trough append and
remove of file objects while not having to care about the src_paths
since it's now a dynamically computed property

2021-02-15 16:25 UTC, waylan requested changes
This looks good. However, we should have some tests added. That fact that we are not getting any failing tests with the below noted issue suggest that we need to add some.

2021-02-15 16:25 UTC, waylan commented on mkdocs/structure/files.py
>          self.src_paths[file.src_path] = file
This line will need to be removed as it would not generate an error.

2021-02-15 18:43 UTC, ultrabug commented
Thanks @waylan ; tests added

2021-02-15 18:48 UTC, ultrabug commented
Added mention to release notes; hopefully to the right place

Cheers

2021-02-16 20:15 UTC, waylan approved these changes

2021-02-16 20:16 UTC, merged